state: small

agents:
  - ramdp
  - rmaxq

episodes: 30
max_steps: 2000
trials: 20
gamma: 0.95

stochastic:
  correct_move: 1.0
  fickle: 0.0
  random_start: false

rmax:
  vmax: 20
  threshold: 1
  max_delta: 0.0001

output:
  csv:
    enabled: true
    output: results/ramdp-small-nonfickle.csv

  chart:
    enabled: true

    width: 450
    height: 200
    columns: 2
    max_height: 700
    trial_mode: MOST_RECENT_AND_AVERAGE

    metrics:
      - STEPS_PER_EPISODE
      - CUMULATIVE_REWARD_PER_EPISODE
      - AVERAGE_EPISODE_REWARD

  visualizer:
    enabled: true
    width: 5
    height: 5
    
